[project]
name = "learn-polars"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "plotly>=6.3.1",
    "polars>=1.34.0",
    "seaborn>=0.13.2",
]
